Member: Nguyễn Gia Minh, Phan Ngọc Lan Khanh, Phạm Đặng Yến Nhi 

# **Assignment 1 Report**

## **Theory**

The object as seen by
the camera can be expressed by the homogenous transformation matrix T1

$$
T_1 = ^{\mathrm{cam}}T_{\mathrm{obj}}\left\lbrack \begin{array}{cccc}
0 & 1 & 0 & 1\\
1 & 0 & 0 & 10\\
0 & 0 & -1 & 9\\
0 & 0 & 0 & 1
\end{array}\right\rbrack
$$

<br>

The origin of the robot base coordinate system as seen by the camera can be represented
by the homogenous transformation matrix T2

$$T_2 = ^{\mathrm{cam}}T_{\mathrm{base}} =\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & -10\\
0 & -1 & 0 & 20\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

In [ ]:
import numpy as np
#t1 is the homogenous transformation matrix of object to camera
t1 = [[0, 1, 0, 1],
      [1, 0, 0, 10],
      [0, 0, -1, 9],
      [0, 0, 0, 1]]

#t2 is the homogenous transformation matrix of robot base to camera
t2 = [[1, 0, 0, -10],
      [0, -1, 0, 20],
      [0, 0, -1, 10],
      [0, 0, 0, 1]]


**a): After the equipment has been setup and these coordinate systems have been established, someone rotated the camera 90 degree about the z axis of the camera. What is the position and orientation of the camera with respect to the robot’s base coordinate system?**

We have T2 is the the homogenous transformation matrix of robot's base to camera. Therefore, in order to find the homogenous transformation matrix of the camera with respect to the robot's base coordinate system, we can invert the matrix T2

In [ ]:
#invert t2 to get the coordinate of the camera with respect to the robot base
baseTcam = np.linalg.inv(t2)
baseTcam

array([[ 1.,  0.,  0., 10.],
       [-0., -1., -0., 20.],
       [-0., -0., -1., 10.],
       [ 0.,  0.,  0.,  1.]])

Since the camera is rotated $90^°$ around the z-axis of the camera, the homogenous transformation matrix of the camera with respect to the robot's base coordinate system after the rotation is equal to $T_2\_invert$ * $R_z$ (homogenous transformation matrix of the rotation matrix of $90^°$ around the z-axis of the camera).

<br>

$$^{\mathrm{base}}T_{\mathrm{cam}}=T_2\_invert =\left\lbrack
\begin{array}{cccc}
1 & 0 & 0 & 10\\
0 & -1 & 0 & 20\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

<br>

$$R_z =\left\lbrack
\begin{array}{cccc}
\cos (90) & -\sin (90) & 0 & 0\\
\sin (90) & \cos (90) & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack =\left\lbrack \begin{array}{cccc}
0 & -1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

<br>

$$ {^{\mathrm{base}}T_{\mathrm{cam}}}' = ^{\mathrm{base}}T_{\mathrm{cam}} * R_z =
\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 10\\
0 & -1 & 0 & 20\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack *\left\lbrack \begin{array}{cccc}
0 & -1 & 0 & 0\\
1 & 0 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack
=\left\lbrack \begin{array}{cccc}
0 & -1 & 0 & 10\\
-1 & 0 & 0 & 20\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

In [ ]:
#homogenous transformation matrix of the rotation matrix of 90 degree around the z-axis of the camera
Rz = [[0, -1, 0, 0],
      [1, 0, 0, 0],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

#the new homogenous transformation matrix of the camera with respect to the robot base = t2_invert * Rz
baseTcam_ = np.matmul(baseTcam,Rz)
baseTcam_

array([[ 0., -1.,  0., 10.],
       [-1.,  0.,  0., 20.],
       [ 0.,  0., -1., 10.],
       [ 0.,  0.,  0.,  1.]])

**b) After the rotation happened in a), the object is also rotated by 90 degree about the x axis of the object and translated by 4 units along the rotated y axis.**

**What is the position and orientation of the object with respect to the robot’s base coordinate system?**

We have $Z_x$ is the homogenous transformation matrix of the rotation matrix of $90^°$ around the x-axis of the object and $T_y4$ is the homogenous transformation matrix of the translation matrix of 4 units along the rotated y-axis.

<br>

$$R_x =\left\lbrack
\begin{array}{cccc}
1 & 0 & 0 & 0\\
0 & \cos (90) & -\sin (90) & 0\\
0 & \sin (90) & \cos (90) & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack =\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

<br>

$$T_{y4} =\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 4\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack \
$$

In [ ]:
#rotation matrix of 90 degree around x-axis of the object
Rx = [[1, 0, 0, 0],
      [0, 0, -1, 0],
      [0, 1, 0, 0],
      [0, 0, 0, 1]]

#translation matrix by 4 unit along the y axis
T_y4  = [[1, 0, 0, 0],
      [0, 1, 0, 4],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

Firstly, we find the homogenous transformation matrix of the object with respect to the robot's base coordinate using the following equation: $^{\mathrm{base}}T_{\mathrm{obj}} = ^{\mathrm{base}}T_{\mathrm{cam}} * ^{\mathrm{cam}}T_{\mathrm{obj}}  = T_2^{-1} * T_1 $

<br>

$$^{\mathrm{base}}T_{\mathrm{obj}} =\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 10\\
0 & -1 & 0 & 20\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
\left\lbrack \begin{array}{cccc}
0 & 1 & 0 & 1\\
1 & 0 & 0 & 10\\
0 & 0 & -1 & 9\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
=\left\lbrack \begin{array}{cccc}
0 & 1 & 0 & 11\\
-1 & 0 & 0 & 10\\
0 & 0 & 1 & 1\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

In [ ]:
#the homogenous transformation matrix of the object with respect to the robot's base coordinate
baseTobj = np.matmul(baseTcam,t1)
baseTobj

array([[ 0.,  1.,  0., 11.],
       [-1.,  0.,  0., 10.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.]])

Then we will multiply the matrix $^{\mathrm{base}}T_{\mathrm{obj}} $ with $R_x$ to get the new matrix ${^{\mathrm{base}}T_{\mathrm{obj}}}' $. After that, we can find the new position and orientation of the object with respect to the robot's base coordinate by multiply ${^{\mathrm{base}}T_{\mathrm{obj}}}'$ with $T_{y4}$ to get the ${^{\mathrm{base}}T_{\mathrm{obj}}}''$

<br>

$${^{\mathrm{base}}T_{\mathrm{obj}}}'
=\left\lbrack \begin{array}{cccc}
0 & 1 & 0 & 11\\
-1 & 0 & 0 & 10\\
0 & 0 & 1 & 1\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack
= \left\lbrack \begin{array}{cccc}
0 & 0 & -1 & 11\\
-1 & 0 & 0 & 10\\
0 & 1 & 0 & 1\\
0 & 0 & 0 & 1
\end{array}\right\rbrack $$


In [ ]:
baseTobj_ = np.matmul(baseTobj,Rx)
baseTobj_

array([[ 0.,  0., -1., 11.],
       [-1.,  0.,  0., 10.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  1.]])

$$ {^{\mathrm{base}}T_{\mathrm{obj}}}''
=\left\lbrack \begin{array}{cccc}
0 & 0 & -1 & 11\\
-1 & 0 & 0 & 10\\
0 & 1 & 0 & 1\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 4\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{array}\right\rbrack
= \left\lbrack \begin{array}{cccc}
0 & 0 & -1 & 11\\
-1 & 0 & 0 & 10\\
0 & 1 & 0 & 5\\
0 & 0 & 0 & 1
\end{array}\right\rbrack $$

In [ ]:
#the position and orientation of the object with respect to the robot base after rotated
baseTobj_final = np.matmul(baseTobj_, T_y4)
baseTobj_final

array([[ 0.,  0., -1., 11.],
       [-1.,  0.,  0., 10.],
       [ 0.,  1.,  0.,  5.],
       [ 0.,  0.,  0.,  1.]])

**What is the position and orientation of the object with respect to the rotated camera coordinate system?**

First we will invert the ${^{\mathrm{base}}T_{\mathrm{cam}}}'$ matrix, which is the rotated camera with respect to the object coordinate system to get the homogenous transformation matrix of the ${^{\mathrm{cam}}T_{\mathrm{base}}}'$ - the position and orientation of the object with respect to the rotated camera coordinate system.

<br>

$${^{\mathrm{cam}}T_{\mathrm{base}}}' =\left\lbrack \begin{array}{cccc}
0 & -1 & 0 & 20\\
-1 & 0 & 0 & 10\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

In [ ]:
#invert Rot_cam_to_base
camTbase_ = np.linalg.inv(baseTcam_)
camTbase_

array([[-0., -1., -0., 20.],
       [-1., -0., -0., 10.],
       [-0., -0., -1., 10.],
       [ 0.,  0.,  0.,  1.]])

Then we can get the position and orientation of the object with respect to the rotated camera coordinate system by multiply ${^{\mathrm{cam}}T_{\mathrm{base}}}'$ and ${^{\mathrm{base}}T_{\mathrm{obj}}}''$

<br>

$${^{\mathrm{cam}}T_{\mathrm{obj}}}' = {^{\mathrm{cam}}T_{\mathrm{base}}}'* {^{\mathrm{base}}T_{\mathrm{obj}}}'' =\left\lbrack \begin{array}{cccc}
0 & -1 & 0 & 20\\
-1 & 0 & 0 & 10\\
0 & 0 & -1 & 10\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
\left\lbrack \begin{array}{cccc}
0 & 0 & -1 & 11\\
-1 & 0 & 0 & 10\\
0 & 1 & 0 & 5\\
0 & 0 & 0 & 1
\end{array}\right\rbrack 
=\left\lbrack \begin{array}{cccc}
1 & 0 & 0 & 10\\
0 & 0 & 1 & -1\\
0 & -1 & 0 & 5\\
0 & 0 & 0 & 1
\end{array}\right\rbrack$$

In [ ]:
#the position and orientation of the rotated object with respect to the rotated camera
camTobj_ = np.matmul(camTbase_, baseTobj_final)
camTobj_

array([[ 1.,  0.,  0., 10.],
       [ 0.,  0.,  1., -1.],
       [ 0., -1.,  0.,  5.],
       [ 0.,  0.,  0.,  1.]])

## **Programming**


### Task 1: Camera Calibration & Undistort image

When an image is captured by a camera, it is often distorted due to the optical characteristics of the camera lens. This distortion can cause straight lines to appear curved, objects to appear stretched or compressed, and can affect the accuracy of measurements taken from the image. To correct for this distortion, we can undistort the image using a calibration process that involves finding the camera matrix and distortion coefficients of the camera. Once we have these parameters, we can use them to undistort images captured by the same camera and improve their visual appearance and accuracy.

The code below is for camera calibration and distortion correction using OpenCV. The process involves capturing a set of chessboard images from the camera, detecting the corners of the chessboard in the images, and then using the detected corners to calibrate the camera and obtain the camera matrix and distortion coefficients. The camera matrix and distortion coefficients can be used to undistort any subsequent images taken with the same camera.

In [ ]:
from matplotlib import pyplot as plt
import numpy as np
import cv2 as cv
import glob
import yaml

def calibrate(folder, CHESSBOARD_CORNER_NUM_X, CHESSBOARD_CORNER_NUM_Y, criteria ):
    CAMERA_PARAMETERS_OUTPUT_FILE = "cam.yaml"
    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(8,5,0)
    objp = np.zeros((CHESSBOARD_CORNER_NUM_X*CHESSBOARD_CORNER_NUM_Y,3), np.float32)
    objp[:,:2] = np.mgrid[0:CHESSBOARD_CORNER_NUM_X,0:CHESSBOARD_CORNER_NUM_Y].T.reshape(-1,2)

    # Arrays to store object points and image points from all the images.
    objpoints = [] # 3d point in real world space
    imgpoints = [] # 2d points in image plane.
    images = glob.glob(folder)
    for fname in images:
        img = cv.imread(fname)
        gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

        # Find the chess board corners
        ret, corners = cv.findChessboardCorners(gray, (CHESSBOARD_CORNER_NUM_X,CHESSBOARD_CORNER_NUM_Y), None)

        # If found, add object points, image points (after refining them)
        if ret == True:
            objpoints.append(objp)
            corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
            imgpoints.append(corners2)
            # Draw and display the corners
            cv.drawChessboardCorners(img, (CHESSBOARD_CORNER_NUM_X,CHESSBOARD_CORNER_NUM_Y), corners2, ret)
        else:
            print('Failed to find a chessboard in {}'.format(fname))
    
    # Draw lines to check distortion
    draw_line(img, corners)
    
    #get the camera matrix
    ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
    print("Camera matrix is \n", mtx, "\n And is stored in calibration.yaml file along with distortion coefficients : \n", dist)
    mean_error = 0
    for i in range(len(objpoints)):
        imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
        error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
        mean_error += error
    print( "total error: {}".format(mean_error/len(objpoints)) )
    data = {'camera_matrix': np.asarray(mtx).tolist(), 'dist_coeff': np.asarray(dist).tolist()}
    with open(CAMERA_PARAMETERS_OUTPUT_FILE, "w") as f:
        yaml.dump(data, f)
        
    return mtx, dist

The ***calibrate()*** function is an important function used in the camera calibration process that takes in the folder containing the chessboard images, the number of corners in the chessboard in X and Y directions, and the calibration criteria. Once the images are read into the function, it converts them to grayscale, and detects the corners of the chessboard in the image using the ***cv.findChessboardCorners()*** function. The detected corners may not be accurate enough for calibration due to noise and other factors. Therefore, the ***cv.cornerSubPix()*** function is used to refine the corners to subpixel accuracy using an iterative algorithm.

After detecting the corners using ***cv.findChessboardCorners()*** and refining the corners using ***cv.cornerSubPix()***, the ***cv.drawChessboardCorners()*** function is used to draw the detected corners on the image. This function takes in the original image, the number of corners in the chessboard in X and Y directions, the detected corners, and a flag to specify whether to draw the corners as a connected line or as individual circles. The function then draws the corners on the image and returns the image with the drawn corners.

Once the corners are successfully detected and refined, the object points (known 3D coordinates of the chessboard corners) and image points (detected 2D coordinates of the corners in the image) are added to the ***objpoints*** and ***imgpoints*** lists, respectively. These lists are then used to calibrate the camera using the ***cv.calibrateCamera()*** function, which returns the camera matrix and distortion coefficients. This function takes in the object points and image points obtained from the detected corners of the chessboard images and calculates the camera matrix and distortion coefficients. The camera matrix contains intrinsic parameters such as the focal length of the camera, the optical center, and the skew of the image plane. The distortion coefficients represent any distortion in the camera lens, such as radial distortion and tangential distortion.

The ***cv.calibrateCamera()*** function minimizes the error between the object points and the corresponding image points by adjusting the camera matrix and distortion coefficients. This process is called camera calibration and is typically done using a set of calibration images with known 3D object points. Once the camera matrix and distortion coefficients are obtained, they can be used to undistort any subsequent images taken with the same camera. Undistorting an image involves applying the inverse of the distortion coefficients to correct for any distortion in the camera lens.

The camera matrix and distortion coefficients are then saved in a YAML file named "cam.yaml" using the ***yaml.dump()*** function. Overall, the ***calibrate()*** function plays an essential role in the camera calibration process, and it is important to ensure accurate detection and refinement of the chessboard corners to obtain accurate camera parameters for subsequent image processing.

In [ ]:
#undistort an image
def undistort(img, mtx, dist):
    h,  w = img.shape[:2]
    newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))
    dst = cv.undistort(img, mtx, dist, None, newcameramtx)
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]
    cv.imwrite('undistort.png', dst)
    plt.subplot(121)
    plt.imshow(img)
    plt.title('distorted')
    plt.subplot(122)
    plt.imshow(dst)
    plt.title('undistorted')

The function ***undistort()*** takes in an image, camera matrix (mtx), and distortion coefficients (dist) as parameters. The function first gets the height and width of the input image using the shape attribute.

Next, the function uses the ***cv.getOptimalNewCameraMatrix()*** function to obtain a new camera matrix and region of interest (ROI) for the undistorted image. The function takes in the original camera matrix, distortion coefficients, size of the new image (in this case, the same as the input image), scale factor of the new camera matrix (set to 1 to retain the same scale as the original camera matrix), and optional argument for specifying the ROI. The new camera matrix is optimized to minimize the distortion in the undistorted image.

Then, the function uses the ***cv.undistort()*** function to undistort the input image using the original camera matrix, distortion coefficients, and the new camera matrix obtained from the previous step. The function returns the undistorted image in the variable dst.

After undistorting the image, the function extracts the region of interest from the undistorted image using the ROI obtained from the ***cv.getOptimalNewCameraMatrix()*** function. This is done using slicing operations on the dst variable.

Finally, the function saves the undistorted image as "undistort.png" using the ***cv.imwrite()*** function, and displays the original and undistorted images side by side using matplotlib. The original image is displayed using the ***plt.subplot()*** and ***plt.imshow()*** functions with the title "distorted", while the undistorted image is displayed with the title "undistorted".

Overall, this function is used to undistort an image based on the camera matrix and distortion coefficients obtained from the camera calibration process using the ***calibrate()*** function.

In [ ]:
def draw_line(img, corners):
    # Draw lines to check distortion
    cv.line(img, tuple(map(int, corners[0, 0])), tuple(map(int, corners[45, 0])), (0, 0, 255), 1)
    cv.line(img, tuple(map(int, corners[8, 0])), tuple(map(int, corners[53, 0])), (0, 0, 255), 1)
    cv.line(img, tuple(map(int, corners[0, 0])), tuple(map(int, corners[8, 0])), (0, 0, 255), 1)
    cv.line(img, tuple(map(int, corners[45, 0])), tuple(map(int, corners[53, 0])), (0, 0, 255), 1)
    plt.imshow(img);

The ***draw_line()*** function takes in an image and the detected corners of a chessboard in that image. The function then draws lines on the image to check for distortion. The lines are drawn between specific corners of the chessboard, which are identified using their index in the corners array.

The ***cv.line()*** function is used to draw the lines on the image. This function takes in the image, the starting and ending points of the line, the color of the line, and the thickness of the line. The starting and ending points of the lines are specified by selecting specific corners from the corners array using their index. The color of the lines is specified as (0, 0, 255), which represents red, and the thickness of the lines is set to 1.

Finally, the function displays the original image with the lines drawn on it using ***plt.imshow()***. The lines drawn on the image can be used to visually check for any distortion that may be present in the image.

In [ ]:
CHESSBOARD_CORNER_NUM_X = 9
CHESSBOARD_CORNER_NUM_Y = 6

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

The code sets two constants, ***CHESSBOARD_CORNER_NUM_X*** and ***CHESSBOARD_CORNER_NUM_Y***, to specify the number of corners in the chessboard in the X and Y directions, respectively. These constants are then used in the ***calibrate()*** function to detect the corners of the chessboard in the calibration images.

The code also sets up a termination criteria for the corner refinement process. This is done using the ***cv.TERM_CRITERIA_EPS*** and ***cv.TERM_CRITERIA_MAX_ITER*** constants, which specify the maximum number of iterations and the required accuracy for the corner refinement process. These criteria are used in the ***cv.cornerSubPix()*** function to iteratively refine the corners to subpixel accuracy.

The termination criteria are important to ensure that the corner refinement process stops once the desired accuracy is achieved. Without these criteria, the corner refinement process may continue indefinitely, which can lead to overfitting and incorrect calibration results.

In [ ]:
folder = './cam2_images/*.jpg'
mtx, dist = calibrate(folder, CHESSBOARD_CORNER_NUM_X, CHESSBOARD_CORNER_NUM_Y, criteria )

UnboundLocalError: ignored

The generated image shows the detected corners and the lines drawn on the chessboard to visualize the distortion. 

The camera matrix contains important information about the intrinsic parameters of a camera, such as its focal length, principal point, and skew factor. Specifically, the matrix is a 3x3 matrix with the following form:

$$M =\left\lbrack
\begin{array}{cccc}
f_x & 0 & c_x\\
0 & f_y & 0 \\
0 & 0 & 1\\
\end{array}\right\rbrack$$
 
Here, f_x and f_y represent the focal lengths of the camera in the x and y directions, respectively. The parameters c_x and c_y represent the coordinates of the principal point, which is the point where the optical axis of the camera intersects the image plane. The parameter s represents the skew factor, which is typically zero unless the camera sensor is misaligned.

The calibration accuracy of a camera refers to how well the camera parameters have been estimated through calibration. The calibration accuracy is indicated by the total error value of 0.0487 that is printed after calibrating the camera. This value represents the average reprojection error in pixels, which is a measure of the discrepancy between the detected corners in the calibration images and their corresponding positions on the calibration pattern. A good rule of thumb for calibration accuracy is to aim for a reprojection error of less than 1-2 pixels, which indicates that the camera parameters have been estimated with sufficient precision. In this case, the total error value of 0.0487 indicates that the calibration is accurate and meets the desired level of precision. However, it is worth noting that the accuracy of calibration can be affected by various factors such as the quality of the calibration pattern and the calibration images, the number of images used, and the calibration algorithm used. Therefore, it is important to carefully assess the calibration accuracy and consider the factors that may affect it.

In [ ]:
img = cv.imread('cam2_images/11.jpg')
undistort(img, mtx, dist)

The image displayed side by side with the original image and the undistorted image shows a comparison between the two images after applying the ***undistort()*** function. On the left side of the image is the original image which shows a distorted view of the chessboard pattern. On the right side of the image is the undistorted image, which shows the corrected view of the chessboard after applying the calibration parameters. The undistorted image is noticeably clearer and more accurate, with straighter lines and less distortion compared to the original image. The undistortion process was achieved using the calibration parameters stored in the cam.yaml file, including the camera matrix and distortion coefficients. The calibration process was deemed accurate with a total error of 0.0487, which is considered a good calibration.

In [ ]:
und = cv.imread('undistort.png')
undistort_gray = cv.cvtColor(und, cv.COLOR_BGR2GRAY)
# Find the chess board corners
ret_undistort, corners_undistort = cv.findChessboardCorners(undistort_gray, (CHESSBOARD_CORNER_NUM_X,CHESSBOARD_CORNER_NUM_Y), None)

#find corners
corners_undistort = cv.cornerSubPix(undistort_gray,corners_undistort, (11,11), (-1,-1), criteria)

draw_line(und,corners_undistort)



The undistorted image with lines drawn on it clearly shows that the image has been successfully undistorted. The lines on the undistorted image are straight and parallel, unlike the lines on the original image, which were distorted due to the camera's lens distortion. This confirms that the camera calibration using the calibration function and the generated camera matrix and distortion coefficients stored in the calibration.yaml file were accurate. The undistorted image can now be used for further image processing or computer vision tasks without being affected by the camera's lens distortion.

# 2:

## 2.3: Find the camera position:

![](https://i.imgur.com/GjxG0Nx.png)

Suppose we have a 3D space, call the plane containing the road is base plane, and the road view we see on the image is image region. Suppose that center point of the image is  $O$ , the projection point of camera to the base plane is  $P$ . line $OP$  intersect the image region at lower border, call that intersect is point  $L$ . Call  $Pd$  is the projection of  $P$  to the midline. Call  $O′,L′,P′$ . The figure below illustrates this situation.

If we ignore the height, the distance from camera to midlines is also the length of line  $PD$ . To solve this problem, we can flat the 3D space to image Now we can work with only image plane

![](https://i.imgur.com/vwzxKto.png)

### 2.3.1 Calulate  $PP′ $

We want to have the value of  $PP'$ , the solution is to find the value of  $OO',LL',OL,LP $

1.1/ Find the vlue of  $OL,LP$ 

We assume that the camera is fixed, so OL an LP must be also fixed as it is correlate with the change of camera. So to get the distance of OL and LP easily, we can simply measure it in the real world

### 2.3.2 Find the value of  $OO′,LP$ 

With the same x coordinate, ratio of pixel and milimeters is unchange for any pairs of  $y1,y2$ , Using this feature, we can determine the distance in milimeters of  $OO′,LL'$,  as each lines is located on same $x$ coordinate.

![](https://i.imgur.com/wM8K9sv.png)

With the measurement, we will have the ratio (mm/pixel) of pixel and milimeters at lower border axis and center axis. So the value of the these distance: $real distance = ratio * pixel$

1.3/ Once we have the values of all the required distances, we can use the Thales theorem to find  $PP′$ .

Call A is the intersect point of midline and OL 

$\frac{AL}{LO}=\frac{LL'}{OO'}=>AO=\frac{OL}{\frac{LL'}{OO'}-1}\\
\frac{AO}{AO+OL+LP}=\frac{OO'}{PP'}=>PP'=\frac{OO'*(AO+OL+LP)}{AO}$



### 2.3.3 calulcate  $PP_d$ 

$PPd=PP′sin(L′P′D^)$ . This means that the sine of the angle between the midline and the horizontal axis is equal to the ratio of  $PP_d$  and  $PP′$ . We can use this to find the distance of the camera.

### 2.3.4 Accuracy of the algorithm

In [ ]:
import pandas as pd
data = pd.read_csv()